# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, max_length=300)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomodation_day_1', models.BooleanField()),
                ('dinner_1', models.BooleanField()),
                ('accomodation_day_2', models.BooleanField()),
                ('breakfast_2', models.BooleanField()),
                ('dinner_2', models.BooleanField()),
                ('accomodation_day_3', models.BooleanField()),
                ('breakfast_3', models.BooleanField()),
                ('dinner_3', models.BooleanField()),
                ('breakfast_4', models.BooleanField()),
                ('contact', models.TextField()),
                ('vegetarian', models.BooleanField()),
                ('payment_accepted', models.BooleanField(default=False)),
                ('shirt_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=5)),
                ('shirt_type', models.CharField(choices=[('m', 'classic'), ('f', 'female')], max_length=1)),
                ('bonus_minutes', models.IntegerField(default=0)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conferences.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='Zosia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='First day')),
                ('active', models.BooleanField(default=False)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(default='')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Place')),
            ],
        ),
    ]
