# Generated by Django 2.2.4 on 2019-09-18 16:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('name', models.TextField(default='Bus')),
            ],
            options={
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, max_length=300)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Zosia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='First day')),
                ('active', models.BooleanField(default=False)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(default='')),
                ('registration_start', models.DateTimeField(verbose_name='Registration for users starts')),
                ('registration_end', models.DateTimeField()),
                ('rooming_start', models.DateTimeField(verbose_name='Users room picking starts')),
                ('rooming_end', models.DateTimeField()),
                ('lecture_registration_start', models.DateTimeField(verbose_name='Registration for lectures starts')),
                ('lecture_registration_end', models.DateTimeField()),
                ('price_accomodation', models.IntegerField(verbose_name='Price for sleeping in hotel, per day')),
                ('price_accomodation_breakfast', models.IntegerField(verbose_name='Price for accomodation + breakfast')),
                ('price_accomodation_dinner', models.IntegerField(verbose_name='Price for accomodation + dinner')),
                ('price_whole_day', models.IntegerField(verbose_name='Price for whole day (accomodation + breakfast + dinner)')),
                ('price_transport', models.IntegerField(verbose_name='Price for transportation')),
                ('price_base', models.IntegerField(default=0, verbose_name='Organisation fee')),
                ('account_number', models.CharField(max_length=32, verbose_name='Organization account for paying')),
                ('account_details', models.TextField(default='', verbose_name='Details for account (name, address)')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conferences.Place')),
            ],
            options={
                'verbose_name': 'Conference',
                'verbose_name_plural': 'Conferences',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomodation_day_1', models.BooleanField(default=False)),
                ('dinner_1', models.BooleanField(default=False)),
                ('accomodation_day_2', models.BooleanField(default=False)),
                ('breakfast_2', models.BooleanField(default=False)),
                ('dinner_2', models.BooleanField(default=False)),
                ('accomodation_day_3', models.BooleanField(default=False)),
                ('breakfast_3', models.BooleanField(default=False)),
                ('dinner_3', models.BooleanField(default=False)),
                ('breakfast_4', models.BooleanField(default=False)),
                ('contact', models.TextField(default='', help_text='For example your phone number')),
                ('information', models.TextField(blank=True, default='', help_text='Here is where you can give us information about yourself that may be important during your trip.')),
                ('vegetarian', models.BooleanField(default=False)),
                ('payment_accepted', models.BooleanField(default=False)),
                ('shirt_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='S', max_length=5)),
                ('shirt_type', models.CharField(choices=[('m', 'classic'), ('f', 'female')], default='m', max_length=1)),
                ('bonus_minutes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)])),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conferences.Bus')),
            ],
            options={
                'verbose_name_plural': 'Users preferences',
            },
        ),
    ]
