# Generated by Django 3.2.22 on 2023-10-29 22:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

import conferences.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, max_length=300)),
                ('address', models.TextField()),
                ('town', models.CharField(default='', help_text='Town displayed in terms and conditions', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Zosia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='First day')),
                ('active', models.BooleanField(default=False)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(default='')),
                ('registration_suspended', models.BooleanField(default=False, verbose_name='Is registration suspended')),
                ('early_registration_start', models.DateTimeField(blank=True, null=True, verbose_name='Registration for early registering users starts')),
                ('registration_start', models.DateTimeField(verbose_name='Registration for users starts')),
                ('registration_end', models.DateTimeField()),
                ('lecture_registration_start', models.DateTimeField(verbose_name='Registration for lectures starts')),
                ('lecture_registration_end', models.DateTimeField()),
                ('rooming_start', models.DateTimeField(verbose_name='Users room picking starts')),
                ('rooming_end', models.DateTimeField()),
                ('price_accommodation', models.IntegerField(verbose_name='Price for sleeping in hotel, per day')),
                ('price_accommodation_breakfast', models.IntegerField(verbose_name='Price for accommodation + breakfast')),
                ('price_accommodation_dinner', models.IntegerField(verbose_name='Price for accommodation + dinner')),
                ('price_whole_day', models.IntegerField(verbose_name='Price for whole day (accommodation + breakfast + dinner)')),
                ('price_transport', models.IntegerField(verbose_name='Price for transportation')),
                ('price_base', models.IntegerField(default=0, verbose_name='Organisation fee')),
                ('account_number', models.CharField(max_length=34, validators=[conferences.models.validate_iban], verbose_name='Organization account for paying')),
                ('account_owner', models.TextField(max_length=100, verbose_name='Account owner name')),
                ('account_bank', models.TextField(max_length=50, verbose_name='Bank name where account has been opened')),
                ('account_address', models.TextField(max_length=150, verbose_name='Account owner address')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conferences', to='conferences.place')),
            ],
            options={
                'verbose_name': 'Conference',
                'verbose_name_plural': 'Conferences',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(400)])),
                ('departure_time', models.DateTimeField()),
                ('name', models.TextField(default='Transport')),
                ('zosia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='conferences.zosia')),
            ],
        ),
    ]
