# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_squashed_0006_auto_20161205_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='zosia',
            name='price_base',
            field=models.IntegerField(default=0, verbose_name='Organisation fee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zosia',
            name='price_transport',
            field=models.IntegerField(default=0, verbose_name='Price for transportation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zosia',
            name='account_number',
            field=models.CharField(max_length=32, verbose_name='Organization account for paying'),
        ),
        migrations.AlterField(
            model_name='zosia',
            name='price_accomodation',
            field=models.IntegerField(verbose_name='Price for sleeping in hotel, per day'),
        ),
        migrations.AlterField(
            model_name='zosia',
            name='price_bonus_for_whole_day',
            field=models.IntegerField(verbose_name='Bonus for picking whole day'),
        ),
        migrations.AlterField(
            model_name='zosia',
            name='price_breakfast',
            field=models.IntegerField(verbose_name='Price for breakfast'),
        ),
        migrations.AlterField(
            model_name='zosia',
            name='price_dinner',
            field=models.IntegerField(verbose_name='Price for dinner'),
        ),
        migrations.AlterField(
            model_name='zosia',
            name='registration_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='zosia',
            name='registration_start',
            field=models.DateField(verbose_name='Registration for users starts'),
        ),
        migrations.AlterField(
            model_name='zosia',
            name='rooming_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='zosia',
            name='rooming_start',
            field=models.DateField(verbose_name='Users room picking starts'),
        ),
    ]
