# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_auto_20161113_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default=('S', 'S'), max_length=5),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='shirt_type',
            field=models.CharField(choices=[('m', 'classic'), ('f', 'female')], default=('m', 'classic'), max_length=1),
        ),
    ]
