# Generated by Django 2.2.4 on 2019-10-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='contact',
            field=models.TextField(default='', help_text="We need some contact to you in case you didn't show up. For example your phone number."),
        ),
    ]
