# Generated by Django 2.2.6 on 2019-10-28 19:19

import conferences.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_alter_field_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='zosia',
            name='account_number',
            field=models.CharField(max_length=34, validators=[conferences.models.validate_iban], verbose_name='Organization account for paying'),
        ),
    ]
