# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_auto_20161123_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='accomodation_day_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='accomodation_day_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='accomodation_day_3',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='breakfast_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='breakfast_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='breakfast_4',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='contact',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='dinner_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='dinner_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='dinner_3',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
