# Generated by Django 3.2.16 on 2022-12-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_zosia_early_registration_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='zosia',
            name='registration_suspended',
            field=models.BooleanField(default=False, verbose_name='Is registration suspended'),
        ),
    ]
