# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_auto_20161210_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zosia',
            old_name='pricea_accomodation_breakfast',
            new_name='price_accomodation_breakfast',
        ),
    ]
