# Generated by Django 2.2.6 on 2019-10-27 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('conferences', '0004_alter_fields_capacity_and_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='time',
            new_name='departure_time',
        ),
    ]
