# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-25 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0005_auto_20161217_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name_plural': 'Buses'},
        ),
        migrations.AlterModelOptions(
            name='userpreferences',
            options={'verbose_name_plural': 'Users preferences'},
        ),
        migrations.AlterModelOptions(
            name='zosia',
            options={'verbose_name': 'Conference', 'verbose_name_plural': 'Conferences'},
        ),
    ]
