# Generated by Django 3.2.16 on 2023-09-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0005_place_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='zosia',
            name='first_discount',
            field=models.IntegerField(default=0, verbose_name='First discount per day'),
        ),
        migrations.AddField(
            model_name='zosia',
            name='first_discount_limit',
            field=models.IntegerField(default=0, verbose_name='Limited number of registered users for first discount'),
        ),
        migrations.AddField(
            model_name='zosia',
            name='price_transport_with_discount',
            field=models.IntegerField(default=0, verbose_name='Price for transportation with discount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zosia',
            name='second_discount',
            field=models.IntegerField(default=0, verbose_name='Second discount per day'),
        ),
        migrations.AddField(
            model_name='zosia',
            name='second_discount_limit',
            field=models.IntegerField(default=0, verbose_name='Limited number of registered users for second discount'),
        ),
        migrations.AddField(
            model_name='zosia',
            name='third_discount',
            field=models.IntegerField(default=0, verbose_name='Third discount per day'),
        ),
        migrations.AddField(
            model_name='zosia',
            name='third_discount_limit',
            field=models.IntegerField(default=0, verbose_name='Limited number of registered users for third discount'),
        ),
    ]
