# Generated by Django 2.2.7 on 2019-11-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0005_rename_field_bus_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zosia',
            name='account_details',
        ),
        migrations.AddField(
            model_name='zosia',
            name='account_address',
            field=models.TextField(default='', max_length=150, verbose_name='Account owner address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zosia',
            name='account_bank',
            field=models.TextField(default='', max_length=50, verbose_name='Bank name where account has been opened'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zosia',
            name='account_owner',
            field=models.TextField(default='', max_length=100, verbose_name='Account owner name'),
            preserve_default=False,
        ),
    ]
