# Generated by Django 2.2.7 on 2019-11-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0005_rename_field_bus_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='accomodation_day_1',
            new_name='accommodation_day_1',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='accomodation_day_2',
            new_name='accommodation_day_2',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='accomodation_day_3',
            new_name='accommodation_day_3',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='breakfast_2',
            new_name='breakfast_day_2',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='breakfast_3',
            new_name='breakfast_day_3',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='breakfast_4',
            new_name='breakfast_day_4',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='dinner_1',
            new_name='dinner_day_1',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='dinner_2',
            new_name='dinner_day_2',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='dinner_3',
            new_name='dinner_day_3',
        ),
        migrations.RenameField(
            model_name='zosia',
            old_name='price_accomodation',
            new_name='price_accommodation',
        ),
        migrations.RemoveField(
            model_name='zosia',
            name='price_accomodation_breakfast',
        ),
        migrations.RemoveField(
            model_name='zosia',
            name='price_accomodation_dinner',
        ),
        migrations.AddField(
            model_name='zosia',
            name='price_accommodation_breakfast',
            field=models.IntegerField(verbose_name='Price for accommodation + breakfast'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zosia',
            name='price_accommodation_dinner',
            field=models.IntegerField(verbose_name='Price for accommodation + dinner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zosia',
            name='price_whole_day',
            field=models.IntegerField(verbose_name='Price for whole day (accommodation + breakfast + dinner)'),
        ),
    ]
