# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0005_auto_20161205_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='zosia',
            name='account_details',
            field=models.TextField(default='', verbose_name='Details for account (name, address)'),
        ),
        migrations.AddField(
            model_name='zosia',
            name='account_number',
            field=models.CharField(default='123', max_length=32, verbose_name='Organization account for paying'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zosia',
            name='price_accomodation',
            field=models.IntegerField(default=1, verbose_name='Price for sleeping in hotel, per day'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zosia',
            name='price_bonus_for_whole_day',
            field=models.IntegerField(default=1, verbose_name='Bonus price for picking whole day'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zosia',
            name='price_breakfast',
            field=models.IntegerField(default=1, verbose_name='Price for breakfast'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zosia',
            name='price_dinner',
            field=models.IntegerField(default=1, verbose_name='Price for dinner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zosia',
            name='registration_end',
            field=models.DateField(default='2016-01-22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zosia',
            name='registration_start',
            field=models.DateField(default='2016-01-22', verbose_name='Registration for users starts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zosia',
            name='rooming_end',
            field=models.DateField(default='2016-01-22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zosia',
            name='rooming_start',
            field=models.DateField(default='2016-01-22', verbose_name='Users room picking starts'),
            preserve_default=False,
        ),
    ]
