# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0006_auto_20161225_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='S', max_length=5),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='shirt_type',
            field=models.CharField(choices=[('m', 'classic'), ('f', 'female')], default='m', max_length=1),
        ),
    ]
