# Generated by Django 3.2.21 on 2023-10-25 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0006_zosia_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Transport',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
