# Generated by Django 2.2.7 on 2019-11-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0006_payment_fields_renaming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zosia',
            name='account_details',
        ),
        migrations.AddField(
            model_name='zosia',
            name='account_address',
            field=models.TextField(max_length=150, verbose_name='Account owner address'),
        ),
        migrations.AddField(
            model_name='zosia',
            name='account_bank',
            field=models.TextField(max_length=50, verbose_name='Bank name where account has been opened'),
        ),
        migrations.AddField(
            model_name='zosia',
            name='account_owner',
            field=models.TextField(max_length=100, verbose_name='Account owner name'),
        ),
    ]
