# Generated by Django 2.2.7 on 2019-12-06 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0007_fields_for_account_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passengers', to='conferences.Bus'),
        ),
    ]
