# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-20 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0009_auto_20170730_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='contact',
            field=models.TextField(default='', help_text='For example your phone number'),
        ),
    ]
