# Generated by Django 2.2.4 on 2019-08-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0012_auto_20190629_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zosia',
            name='lecture_registration_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='zosia',
            name='lecture_registration_start',
            field=models.DateTimeField(verbose_name='Registration for lectures starts'),
        ),
        migrations.AlterField(
            model_name='zosia',
            name='registration_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='zosia',
            name='registration_start',
            field=models.DateTimeField(verbose_name='Registration for users starts'),
        ),
        migrations.AlterField(
            model_name='zosia',
            name='rooming_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='zosia',
            name='rooming_start',
            field=models.DateTimeField(verbose_name='Users room picking starts'),
        ),
    ]
