# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                # ('logo', models.ImageField(upload_to='sponsors', verbose_name='Logo')),
                ('path_to_logo', models.CharField(max_length=300, unique=True, verbose_name='Path to logo')),

            ],
        ),
    ]
