# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 23:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0003_room_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(through='rooms.UserRoom', to=settings.AUTH_USER_MODEL),
        ),
    ]
