# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 14:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('conferences', '0001_initial'), ('conferences', '0002_auto_20161113_1905'), ('conferences', '0003_auto_20161123_2002'), ('conferences', '0004_auto_20161127_1127'), ('conferences', '0005_auto_20161205_1341'), ('conferences', '0006_auto_20161205_1453')]

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, max_length=300)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomodation_day_1', models.BooleanField()),
                ('dinner_1', models.BooleanField()),
                ('accomodation_day_2', models.BooleanField()),
                ('breakfast_2', models.BooleanField()),
                ('dinner_2', models.BooleanField()),
                ('accomodation_day_3', models.BooleanField()),
                ('breakfast_3', models.BooleanField()),
                ('dinner_3', models.BooleanField()),
                ('breakfast_4', models.BooleanField()),
                ('contact', models.TextField()),
                ('vegetarian', models.BooleanField()),
                ('payment_accepted', models.BooleanField(default=False)),
                ('shirt_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=5)),
                ('shirt_type', models.CharField(choices=[('m', 'classic'), ('f', 'female')], max_length=1)),
                ('bonus_minutes', models.IntegerField(default=0)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conferences.Bus')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zosia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='First day')),
                ('active', models.BooleanField(default=False)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(default='')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Place')),
                ('account_details', models.TextField(default='', verbose_name='Details for account (name, address)')),
                ('account_number', models.CharField(default='123', max_length=32, verbose_name='Organization account for paying')),
                ('price_accomodation', models.IntegerField(default=1, verbose_name='Price for sleeping in hotel, per day')),
                ('price_bonus_for_whole_day', models.IntegerField(default=1, verbose_name='Bonus price for picking whole day')),
                ('price_breakfast', models.IntegerField(default=1, verbose_name='Price for breakfast')),
                ('price_dinner', models.IntegerField(default=1, verbose_name='Price for dinner')),
                ('registration_end', models.DateField(default='2016-01-22')),
                ('registration_start', models.DateField(default='2016-01-22', verbose_name='Registration for users starts')),
                ('rooming_end', models.DateField(default='2016-01-22')),
                ('rooming_start', models.DateField(default='2016-01-22', verbose_name='Users room picking starts')),
            ],
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='zosia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Zosia'),
        ),
        migrations.AddField(
            model_name='bus',
            name='zosia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Zosia'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default=('S', 'S'), max_length=5),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='shirt_type',
            field=models.CharField(choices=[('m', 'classic'), ('f', 'female')], default=('m', 'classic'), max_length=1),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='accomodation_day_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='accomodation_day_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='accomodation_day_3',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='breakfast_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='breakfast_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='breakfast_4',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='contact',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='dinner_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='dinner_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='dinner_3',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Organization'),
        ),
    ]
