# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=300)),
                ('place_url', models.CharField(max_length=300)),
                ('place_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Zosia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='First day')),
                ('end_date', models.DateField(verbose_name='Last day')),
                ('active', models.BooleanField(default=False)),
                ('banner', models.ImageField(upload_to='')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Place')),
            ],
        ),
    ]
