# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_auto_20161205_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zosia',
            name='price_bonus_for_whole_day',
        ),
        migrations.RemoveField(
            model_name='zosia',
            name='price_breakfast',
        ),
        migrations.RemoveField(
            model_name='zosia',
            name='price_dinner',
        ),
        migrations.AddField(
            model_name='zosia',
            name='lecture_registration_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zosia',
            name='lecture_registration_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Registration for lectures starts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zosia',
            name='price_accomodation_dinner',
            field=models.IntegerField(default=0, verbose_name='Price for accomodation + dinner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zosia',
            name='price_whole_day',
            field=models.IntegerField(default=0, verbose_name='Price for whole day (accomodation + breakfast + dinner)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zosia',
            name='pricea_accomodation_breakfast',
            field=models.IntegerField(default=0, verbose_name='Price for accomodation + breakfast'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='accomodation_day_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='accomodation_day_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='accomodation_day_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='breakfast_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='dinner_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='dinner_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='dinner_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='zosia',
            name='price_base',
            field=models.IntegerField(default=0, verbose_name='Organisation fee'),
        ),
    ]
