# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_auto_20161019_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
