# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 14:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conferences', '0003_auto_20161023_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPrefences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomodation_day_1', models.BooleanField()),
                ('dinner_1', models.BooleanField()),
                ('accomodation_day_2', models.BooleanField()),
                ('breakfast_2', models.BooleanField()),
                ('dinner_2', models.BooleanField()),
                ('accomodation_day_3', models.BooleanField()),
                ('breakfast_3', models.BooleanField()),
                ('dinner_3', models.BooleanField()),
                ('breakfast_4', models.BooleanField()),
                ('contact', models.TextField()),
                ('vegetarian', models.BooleanField()),
                ('payment_accepted', models.BooleanField(default=False)),
                ('shirt_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=5)),
                ('shirt_type', models.CharField(choices=[('m', 'classic'), ('f', 'female')], max_length=1)),
                ('bonus_minutes', models.IntegerField(default=0)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conferences.Bus')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='zosia',
            name='end_date',
        ),
        migrations.AddField(
            model_name='zosia',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprefences',
            name='zosia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Zosia'),
        ),
        migrations.AddField(
            model_name='bus',
            name='zosia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Zosia'),
        ),
    ]
