# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0004_auto_20161109_1413'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPrefences',
            new_name='UserPreferences',
        ),
    ]
