# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-16 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0007_auto_20170115_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='information',
            field=models.TextField(blank=True, default='', help_text='Here is where you can give us information about yourselfthat may be important during your trip.'),
        ),
    ]
