# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-30 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0008_userpreferences_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='zosia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='conferences.Zosia'),
        ),
    ]
