# Generated by Django 3.2.25 on 2024-04-25 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests', models.TextField(blank=True, help_text='Your requests, suggestions or comments intended for organizers', max_length=800, null=True, verbose_name='Requests or comments')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('accepted', models.BooleanField(default=False, verbose_name='Accepted')),
                ('priority', models.IntegerField(default=99, help_text='Set order on all lectures page')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('abstract', models.TextField(max_length=2048, verbose_name='Abstract')),
                ('lecture_type', models.CharField(choices=[('Lecture', 'Lecture'), ('Workshop', 'Workshop')], max_length=10, verbose_name='Type')),
                ('duration', models.PositiveSmallIntegerField(choices=[(10, '10'), (15, '15'), (20, '20'), (30, '30'), (45, '45'), (60, '60'), (75, '75'), (90, '90'), (120, '120')], help_text="Please remember that organizers <u>ARE ALLOWED</u> to cut you off during your lecture/workshop when you're out of declared time!", verbose_name='Duration (in minutes)')),
                ('events', models.TextField(blank=True, help_text="Are you planning any event after your lecture/workshop (e.g. pizza, drinks, games, recruitment)? <b>TELL US ABOUT IT!</b> Beware that organizers <u>WON'T ALLOW</u> you to arrange your event if you don't announce it here!", max_length=800, null=True, verbose_name='Additional events')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Authors description')),
                ('supporters_names', models.TextField(blank=True, default='', help_text="Write here the names of people that you'd like to present your lecture/workshop with. The organizers will then assign their accounts to your lecture/workshop.", max_length=500, verbose_name="Supporting authors' names")),
            ],
            options={
                'verbose_name': 'Lecture',
                'verbose_name_plural': 'Lectures',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='You can use html tags and materializecss classes', verbose_name='content')),
                ('zosia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='conferences.zosia', verbose_name='Conference')),
            ],
        ),
    ]
