# Generated by Django 3.2.25 on 2024-04-25 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0001_initial'),
        ('conferences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='supporting_authors',
            field=models.ManyToManyField(blank=True, related_name='lectures_supporting', to=settings.AUTH_USER_MODEL, verbose_name='Supporting authors'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='zosia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='conferences.zosia', verbose_name='Conference'),
        ),
    ]
