# Generated by Django 2.2.6 on 2019-10-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='duration',
            field=models.PositiveSmallIntegerField(choices=[(10, '10'), (15, '15'), (20, '20'), (30, '30'), (45, '45'), (60, '60'), (75, '75'), (90, '90'), (120, '120')], verbose_name='Duration (in minutes)'),
        ),
    ]
