# Generated by Django 2.2.10 on 2020-02-16 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='zosia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='conferences.Zosia', verbose_name='Conference'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='zosia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='conferences.Zosia', verbose_name='Conference'),
        ),
    ]
