# Generated by Django 2.2.28 on 2022-11-24 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_related_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='person_type',
        ),
    ]
