# Generated by Django 2.2.7 on 2019-11-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_add_styling_to_helper_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='duration',
            field=models.PositiveSmallIntegerField(choices=[(10, '10'), (15, '15'), (20, '20'), (30, '30'), (45, '45'), (60, '60'), (75, '75'), (90, '90'), (120, '120')], help_text="Please remember that organizers <u>ARE ALLOWED</u> to cut you off during your lecture or workshop when you're out of declared time!", verbose_name='Duration (in minutes)'),
        ),
    ]
