# Generated by Django 2.2.7 on 2019-12-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0006_alter_field_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='person_type',
            field=models.CharField(choices=[('0', 'Sponsor'), ('1', 'Guest'), ('2', 'Normal')], default='2', max_length=1, verbose_name='Person type'),
        ),
    ]
