# Generated by Django 2.2.3 on 2019-07-24 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rooms', '0005_remove_room_zosia'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroom',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
