# Generated by Django 2.2.3 on 2019-07-24 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_room_zosia'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroom',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
