# Generated by Django 2.2.3 on 2019-07-25 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0006_userroom_joined_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
        migrations.AddField(
            model_name='room',
            name='available_beds_double',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='available_beds_single',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='beds_double',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='beds_single',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(related_name='room_of_user', through='rooms.UserRoom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userroom',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
