# Generated by Django 2.2.3 on 2019-07-22 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_room_zosia'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroom',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
