# Generated by Django 2.2.3 on 2019-07-25 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_rooms_add_beds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='lock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.RoomLock'),
        ),
    ]
