# Generated by Django 2.2.4 on 2019-08-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_field_lock_on_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available_beds_double',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='available_beds_single',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds_double',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds_single',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
