runtime: python310
entrypoint: ./run.sh $PORT

# 512 MB of RAM
instance_class: F2

handlers:
- url: /static
  static_dir: static/

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  DJANGO_ENV: prod
  DJANGO_SETTINGS_MODULE: zosia16.settings.prod
  HOSTS: zosia.org,www.zosia.org
  PYTHONUNBUFFERED: 1
