# Generated by Django 3.2.25 on 2024-04-25 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of the boardgame')),
                ('votes_amount', models.PositiveSmallIntegerField(default=0)),
                ('accepted', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=200, verbose_name='Url to boardgamegeek.com')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardgame_votes', to='boardgames.boardgame')),
            ],
        ),
    ]
