# Generated by Django 2.2.5 on 2019-09-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=200,
                                          verbose_name='Name')),
                ('votes', models.PositiveSmallIntegerField(default=0)),
                ('state', models.CharField(choices=[
                 ('A', 'accepted'), ('S', 'suggested')], default='S',
                  max_length=1)),
            ],
        ),
    ]
