# Generated by Django 2.2.9 on 2020-02-02 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'ordering': ['-votes_amount']},
        ),
    ]
