# Generated by Django 2.2.5 on 2019-09-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'ordering': ['votes']},
        ),
    ]
