# Generated by Django 2.2.8 on 2020-01-08 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boardgames', '0002_auto_20190921_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'ordering': ['state', '-votes']},
        ),
        migrations.RenameField(
            model_name='boardgame',
            old_name='votes',
            new_name='votes_amount',
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardgames.Boardgame')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='voter')),
            ],
        ),
    ]
