# Generated by Django 2.2.28 on 2022-11-24 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0002_alter_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={},
        ),
        migrations.AlterField(
            model_name='vote',
            name='boardgame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='boardgame_votes', to='boardgames.Boardgame'),
        ),
    ]
