# Generated by Django 2.2.8 on 2020-01-08 16:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boardgames', '0003_auto_20200108_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Votes',
            new_name='Vote',
        ),
        migrations.AlterModelOptions(
            name='boardgame',
            options={'ordering': ['state', '-votes_amount']},
        ),
    ]
