# Generated by Django 2.2.8 on 2020-01-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0006_auto_20200120_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'ordering': ['accepted', '-votes_amount']},
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='state',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
