# Generated by Django 2.2.9 on 2020-01-30 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boardgames', '0007_auto_20200121_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='url',
            field=models.CharField(max_length=200, verbose_name='Url to boardgamegeek.com'),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name of the boardgame'),
        ),
    ]
