from django.urls import re_path

from conferences import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^terms/$', views.terms_and_conditions, name='terms_and_conditions'),
    re_path(r'^privacy/$', views.privacy_policy, name='privacy_policy'),
    re_path(r'^panel/$', views.admin_panel, name='admin'),
    re_path(r'^transport/$', views.transport, name='transport'),
    re_path(r'^transport/add/$', views.transport_add, name='transport_add'),
    re_path(r'^transport/list/transport_by_user$', views.list_csv_transport_by_user,
            name='list_csv_transport_by_user'),
    re_path(r'^transport/list/users_by_transport/all$', views.list_csv_all_users_by_transport,
            name='list_csv_all_users_by_transport'),
    re_path(r'^transport/list/users_by_transport/paid$', views.list_csv_paid_users_by_transport,
            name='list_csv_paid_users_by_transport'),
    re_path(r'^transport/list/users_by_transport/paid/students$',
            views.list_csv_paid_students_by_transport,
            name='list_csv_paid_students_by_transport'),
    re_path(r'^transport/list/users_by_transport/paid/non_students$',
            views.list_csv_paid_non_students_by_transport,
            name='list_csv_paid_non_students_by_transport'),
    re_path(r'^transport/(?P<pk>\d+)/update/$', views.transport_add, name='transport_update'),
    re_path(r'^transport/(?P<pk>\d+)/people/$', views.transport_people, name='transport_people'),
    re_path(r'^conferences/$', views.conferences, name='conferences'),
    re_path(r'^conferences/add/$', views.update_zosia, name='zosia_add'),
    re_path(r'^conferences/(?P<pk>\d+)/update/$', views.update_zosia, name='zosia_update'),
    re_path(r'^conferences/export/shirts/$', views.export_shirts, name='export_shirts'),
    re_path(r'^conferences/export/data/$', views.export_data, name='export_data'),
    re_path(r'^place/$', views.place, name='place'),
    re_path(r'^place/add/$', views.place_add, name='place_add'),
    re_path(r'^place/(?P<pk>\d+)/update/$', views.place_add, name='place_update'),
    re_path(r'^statistics/$', views.statistics, name='statistics'),
    re_path(r'^signup_rules/$', views.sign_up_rules_for_invited, name='invited'),
]
