# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0002_auto_20161113_1905'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, help_text='Your suggestions, requests and comments intended for organizers and a lot more,', max_length=800, null=True, verbose_name='Information')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('accepted', models.BooleanField(default=False, verbose_name='Accepted')),
                ('order', models.IntegerField(default=99)),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('abstract', models.CharField(max_length=2048, verbose_name='Abstract')),
                ('duration', models.CharField(choices=[('5', '5'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('100', 'Other')], max_length=3, verbose_name='Duration')),
                ('lecture_type', models.CharField(choices=[('0', 'Lecture'), ('1', 'Workshop')], max_length=1, verbose_name='Type')),
                ('person_type', models.CharField(choices=[('0', 'Sponsor'), ('1', 'Guest'), ('2', 'Normal')], max_length=1, verbose_name='Person type')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Author description')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('zosia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Zosia', verbose_name='Conference')),
            ],
            options={
                'verbose_name_plural': 'Lectures',
                'verbose_name': 'Lecture',
                'ordering': ['order', 'id'],
            },
        ),
    ]
