# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='content',
            field=models.TextField(help_text='You can use html tags and materializecss classes', verbose_name='content'),
        ),
    ]
