# Generated by Django 2.2.9 on 2020-01-22 17:07

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hash',
            field=models.CharField(default=None, max_length=64, unique=True, validators=[users.models.validate_hash], verbose_name='hash'),
        ),
    ]
