# Generated by Django 3.2.16 on 2022-12-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_user_person_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='S', max_length=5),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='shirt_type',
            field=models.CharField(choices=[('m', 'classic')], default='m', help_text='<b>This year all shirts are in one type only (classic).</b>', max_length=1),
        ),
    ]
