# Generated by Django 3.2.16 on 2023-01-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_shirt_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='person_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Guest', 'Guest'), ('Sponsor', 'Sponsor'), ('Early_registering', 'Early registering'), ('Organizer', 'Organizer')], default='Normal', max_length=20, verbose_name='person type'),
        ),
    ]
