# Generated by Django 3.2.16 on 2023-09-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_person_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='transport_baggage',
            field=models.BooleanField(default=False),
        ),
    ]
