# Generated by Django 3.2.16 on 2023-09-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='discount_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='transport_baggage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='student_number',
            field=models.TextField(blank=True, default='', help_text='Providing false information risks removal of your application with no refund.'),
        ),
    ]
