# Generated by Django 2.2.3 on 2019-07-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_create_roombeds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='zosia',
        ),
    ]
