# Generated by Django 3.2.22 on 2023-10-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('path_to_logo', models.CharField(max_length=300, unique=True, verbose_name='Path to logo')),
                ('sponsor_type', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=10, verbose_name='Type')),
            ],
        ),
    ]
