# Generated by Django 2.2.2 on 2019-06-29 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0011_bus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zosia',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conferences.Place'),
        ),
    ]
