# Generated by Django 3.2.25 on 2024-04-25 22:55

from django.db import migrations, models

import organizers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, validators=[organizers.models.validate_phone_number], verbose_name='Phone number')),
            ],
        ),
    ]
