# Generated by Django 3.2.16 on 2023-02-01 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizercontact',
            name='user',
            field=models.OneToOneField(limit_choices_to={'person_type': 'Organizer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
