# Generated by Django 3.2.16 on 2023-01-20 18:48

from django.db import migrations, models
import organizers.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizercontact',
            name='phone_number',
            field=models.CharField(max_length=9, validators=[organizers.models.validate_phone_number], verbose_name='Phone number'),
        ),
    ]
